### PR TITLE
added RNN implementation using tf 2.0

### PR DESCRIPTION
**Pull request by soumya997**
Hi, @animenon I have added RNN implementation of tf 2.0 under `ML_AND_DL/tensorflow_2` .
issue number #12 
Please add `hacktoberfest-accepted` before merging 😃

### CODE REVIEW

**Comment by animenon** [comment]
@soumya997 I see that you have added a ipynb, the repo is for documents so it would be better is you could use markdown(.md) to document the required steps for a beginner. You can keep the notebook but a markdown with the details would be ideal.

**Comment by soumya997** [comment]
Ok, sir (@animenon) I will change and make a md version of it.
I guess you need to add the `hacktoberfest-accepted` label, not `hacktoberfest`.
and is the documentation of my notebook ok, or do I have to make some changes?
Should add the outputs of a cell along with the code too?

**Comment by animenon** [comment]
@soumya997 yes do add the outputs to the ipynb.

Note: The label required in `hacktoberfest` as this repo follows the approval process  ([read doc](https://hacktoberfest.digitalocean.com/hacktoberfest-update)).

**Comment by animenon** [comment]
You don't need to raise a new PR for each change, just update the existing PR.
Read about Git here: [Git - version control](https://github.com/techfaqs/Tech-FAQs/tree/master/git)

**Pull request closed without merging**
