### PR TITLE
why and how to use Git?

### PR DESCRIPTION
**Pull request by chidsss**
why and how to use Git

### CODE REVIEW

**Comment by animenon** [comment]
@chidsss you may add examples of git commands.
Thanks was looking into #1

**Comment by chidsss** [comment]
[ Contents of this comment were added to [git_cheatsheet.md](https://github.com/animenon/Tech-FAQs/blob/git/git/git_cheatsheet.md) ]

**Comment by animenon** [comment]
@chidsss Please add it to the file and commit :)

**Comment by chidsss** [comment]
@animenon please im new to this can you tell me how to go about it. thanks

**Comment by animenon** [comment]
@chidsss  sure, in short you have to:
1. Fork it!
    (Maybe `git clone <git/https_link_to_repo>` in local)
2. Create your feature branch: `git checkout -b <my-new-branch>`
3. Commit your changes: `git commit -m 'Added some feature'`
     (before the commit `git add <file_name_to_add_to_commit>`)
4. Push to the branch: `git push origin <my-new-branch>`
5. Submit a pull request!

 Please go though the beginners section in [CONTRIBUTING.md](https://github.com/animenon/Tech-FAQs/blob/master/CONTRIBUTING.md#for-beginners).

**Comment by animenon** [comment]
@chidsss I have added the commands into a file `git_cheatsheet.md` here: https://github.com/animenon/Tech-FAQs/tree/git/git
Feel free to edit/format it and raise a Pull Request. All you have to do is click on file you wish to edit, then choose the edit option from 
image
Change the file as necessary.
Then commit changes (this will automatically create a branch and raise a PR for you).

**Comment by chidsss** [comment]
thank you...that was super helpful and PR RAISED

**Pull request merged**
